services:
  apache:
    image: httpd:alpine
    container_name: apache-${APACHE_PROFILE}
    restart: unless-stopped
    networks:
      - webnet
    ports:
      - "40080:80"
      - "40443:443"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./certs:/usr/local/apache2/certs
    depends_on:
      - webapp

  acme:
    image: neilpang/acme.sh
    container_name: acme-${APACHE_PROFILE}
    restart: "no"
    networks:
      - webnet
    volumes:
      - ./certs:/acme.sh
      - ./acme-dns-hooks:/root/.acme.sh/dnsapi
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - MOUSETRAP_API_URL=${MOUSETRAP_API_URL}
      - MOUSETRAP_TOKEN=${MOUSETRAP_TOKEN}
      - MOUSETRAP_ZONE=${MOUSETRAP_ZONE}
    # Using the default entrypoint of neilpang/acme.sh
    command: --renew -d ${APP_DOMAIN} --server letsencrypt_test --dns dns_mousetrap --debug 2

  webapp:
    image: nginx:alpine
    container_name: webapp-${APACHE_PROFILE}
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
