services:

  acme:
    image: neilpang/acme.sh
    container_name: acme
    command: daemon
    volumes:
      - ./certs:/acme.sh
      - ./acme-dns-hooks:/root/.acme.sh/dnsapi
    environment:
      - MOUSETRAP_API_URL=${MOUSETRAP_API_URL}
      - MOUSETRAP_TOKEN=${MOUSETRAP_TOKEN}
      - MOUSETRAP_ZONE=${MOUSETRAP_ZONE}
