services:

  acme:
    image: neilpang/acme.sh
    container_name: acme
    volumes:
      - ./certs:/acme.sh
      - ./acme-dns-hooks:/root/.acme.sh/dnsapi
      # IMPORTANT: mount Docker Socket so acme.sh can reload the webserver
      # - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MOUSETRAP_API_URL=${MOUSETRAP_API_URL}
      - MOUSETRAP_TOKEN=${MOUSETRAP_TOKEN}
      - MOUSETRAP_ZONE=${MOUSETRAP_ZONE}
